In [40]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [50]:
data = gpd.read_file("./Kondisi_100/KONDISI_100.shp")
data.PERKERASAN.replace("RIGID", "BETON", inplace=True)
np.unique(data.PERKERASAN)
data.to_file("./Kondisi_100/KONDISI_100.shp")

In [56]:
if "RIGID" in np.unique(data.PERKERASAN):
    if "BETON" not in np.unique(data.PERKERASAN)
        data.PERKERASAN.replace("RIGID", "BETON", inplace=True) 
        data.to_file("./Kondisi_100/KONDISI_100.shp")

True

In [37]:
import os
if not os.path.isfile("./table_stat.csv"):
    print("tidak ada")
else:
    print("ada")

ada

In [1]:
from bokeh.plotting import figure, curdoc
from bokeh.layouts import column
from bokeh.models import ColumnDataSource

TOOLS = ["tap"]
p = figure(title="Some Figure", tools=TOOLS)

source = ColumnDataSource(dict(
    x=[[1, 3, 2], [3, 4, 6, 6]],
    y=[[2, 1, 4], [4, 7, 8, 5]],
    name=['A', 'B'],color=["firebrick", "navy"],
    alpha=[0.8,0.3],line_width=[3,3]))

pglyph = p.patches('x', 'y', color="color", alpha="alpha",
                   line_width="line_width", source=source)

def callback(attr, old, new):
    # The index of the selected glyph is : new['1d']['indices'][0]
    selections = new['1d']['indices']
    print("Number of selections:{}".format(len(selections)))
    for index in selections:
        patch_name =  source.data['name'][index]
        print("TapTool callback executed on Patch {}".format(patch_name))

pglyph.data_source.on_change('selected',callback)

curdoc().add_root(column(p))

In [174]:
data = gpd.read_file("Jalan_Nasional/JALAN_NASIONAL.shp")
data2 = gpd.read_file("Kondisi_100/KONDISI_100.shp")

In [154]:
select.iloc[0]

STA                                           90.09999999999999
LEBAR_JALA                                                    7
BAHU_KIRI                                                     2
BAHU_KANAN                                                    2
TROTOAR_KI                                                    0
TROTOAR_KA                                                    0
PERKERASAN                                                ASPAL
IRI                                                           5
SDI                                                           3
KONDISI_IR                                               SEDANG
KONDISI_SD                                                 BAIK
X                                                        341486
Y                                                   9.79384e+06
RUAS                                                      N.001
P_SEGMEN                                                   0.05
KEY                                                         001
LAYER                                                     JALAN
NO                                                            1
NO_RUAS                                                    001.
NAMA_RUAS                        BTS. PROV. JAMBI - PENINGGALAN
PANJANG                                                   90.15
LINTAS                                             Lintas Timur
LINTAS_RUA                                   Lintas Timur Jambi
TITIK_AWAL                                         Patok Km 146
TITIK_AKHI                             Gapura Batas Prov. Jambi
PANJANG_RE                                               356675
geometry      LINESTRING (341442.2624541589 9793865.27823417...
Name: 0, dtype: object

In [1]:
class statistik:
    import geopandas as gpd
    import pandas as pd
    import numpy as np
        
    def __init__(self, file :str):
        self.file = file
        self.data = self.gpd.read_file(file)
        self.panda = self.pd.read_csv("./table_stat.csv", index_col=0)
        
        self.data.P_SEGMEN = self.data.P_SEGMEN.astype(self.np.float64)
        self.data.LEBAR_JALA = self.data.LEBAR_JALA.astype(self.np.float32)
        self.data.BAHU_KIRI = self.data.BAHU_KIRI.astype(self.np.float32)
        self.data.BAHU_KANAN = self.data.BAHU_KANAN.astype(self.np.float32)
        self.data.TROTOAR_KI = self.data.TROTOAR_KI.astype(self.np.float32)
        self.data.TROTOAR_KA = self.data.TROTOAR_KA.astype(self.np.float32)
        self.data.IRI = self.data.IRI.astype(self.np.uint8)
        self.data.SDI = self.data.SDI.astype(self.np.uint8)

    def format_uang(self, angka: float):
        return "{:,.2f}".format(angka)

    def select(self, NO: str):
        selected = self.data[self.data.eq(NO).any(1)]
        return selected

    def nama_ruas(self, selected):
        return selected.loc[selected.index[1]].NAMA_RUAS

    def panjang(self, selected):
        return selected.P_SEGMEN.sum()

    def rata_kondisi(self, selected):
        P_SEG = selected.P_SEGMEN
        IRI = (P_SEG * selected.IRI).sum()
        SDI = (P_SEG * selected.SDI).sum()
        LEBAR = (P_SEG * selected.LEBAR_JALA).sum()
        N_DATA = P_SEG.sum()
        
        return IRI/N_DATA, SDI/N_DATA, LEBAR/N_DATA

    def panjang_per_kondisi(self, selected, col_name:str):
        baik = 0
        sedang = 0
        rusak_ringan = 0
        rusak_berat = 0

        for i, row in selected.iterrows():
            if (row[col_name] == "BAIK"):
                baik = baik + row["P_SEGMEN"]
            elif (row[col_name] == "SEDANG"):
                sedang = sedang + row["P_SEGMEN"]
            elif (row[col_name] == "RUSAK RINGAN"):
                rusak_ringan = rusak_ringan + row["P_SEGMEN"]
            elif (row[col_name] == "RUSAK BERAT"):
                rusak_berat = rusak_berat + row["P_SEGMEN"]

        baik = baik
        sedang = sedang
        rusak_ringan = rusak_ringan
        rusak_berat = rusak_berat
        total = baik + sedang + rusak_ringan + rusak_berat

        return baik, sedang, rusak_ringan, rusak_berat, total

    def lebar(self, selected):
        less_enam = 0
        enam_tujuh = 0
        tujuh_empat_belas = 0
        greater_empat_belas = 0
        
        for i, row in selected.iterrows():
            if (row["LEBAR_JALA"] <= 6):
                less_enam = less_enam + row["P_SEGMEN"]
            elif(row["LEBAR_JALA"] > 6 and row["LEBAR_JALA"] <= 7):
                enam_tujuh = enam_tujuh + row["P_SEGMEN"]
            elif(row["LEBAR_JALA"] > 7 and row["LEBAR_JALA"] <= 14):
                tujuh_empat_belas = tujuh_empat_belas + row["P_SEGMEN"]
            elif(row["LEBAR_JALA"] > 14):
                greater_empat_belas = greater_empat_belas + row["P_SEGMEN"]

        less_enam = less_enam
        enam_tujuh = enam_tujuh
        tujuh_empat_belas = tujuh_empat_belas
        greater_empat_belas = greater_empat_belas
        total = less_enam + enam_tujuh + tujuh_empat_belas + greater_empat_belas

        return less_enam, enam_tujuh, tujuh_empat_belas, greater_empat_belas, total

    def biaya(self, data_kondisi, sedang = 50_000_000, rusak_berat = 8_640_000_000, rusak_ringan = 4_096_000_000, baik = 50_000_000):
        return data_kondisi[0] * baik + data_kondisi[1] * sedang + data_kondisi[2] * rusak_ringan + data_kondisi[3] * rusak_berat
    
    def _indexInTable(self, NO_RUAS: str):
        index = self.panda.loc[self.panda['NO'] == str(NO_RUAS)].index[0]
        return index
        
    def generate(self):
        kolom = ["NO", "RUAS", "PANJANG", "IRI_RATA", "SDI_RATA", "LEBAR_RATA", "IRI_BAIK", "IRI_SEDANG", 
         "IRI_RUSAK_RINGAN","IRI_RUSAK_BERAT", "IRI_TOTAL", "SDI_BAIK", "SDI_SEDANG", "SDI_RUSAK_RINGAN", 
         "SDI_RUSAK_BERAT", "SDI_TOTAL","LESS_ENAM", "ENAM_TUJUH", "TUJUH_EMPAT_BELAS", 
         "GREATER_EMPAT_BELAS", "PANJANG_TOTAL", "BIAYA_IRI", "BIAYA_SDI"]
        df = self.pd.DataFrame(columns=kolom) 
        nomor_ruas = self.data.NO_RUAS.unique()
        
        for nomor in nomor_ruas:
            NO = str(nomor)
            SELECTED = self.select(NO)
            RUAS = self.nama_ruas(SELECTED)
            PANJANG = self.panjang(SELECTED)
            IRI_RATA, SDI_RATA, LEBAR_RATA = self.rata_kondisi(SELECTED)
            IRI_BAIK, IRI_SEDANG, IRI_RUSAK_RINGAN, IRI_RUSAK_BERAT, IRI_TOTAL = self.panjang_per_kondisi(SELECTED, "KONDISI_IR")
            SDI_BAIK, SDI_SEDANG, SDI_RUSAK_RINGAN, SDI_RUSAK_BERAT, SDI_TOTAL = self.panjang_per_kondisi(SELECTED, "KONDISI_SD")
            LESS_ENAM, ENAM_TUJUH, TUJUH_EMPAT_BELAS, GREATER_EMPAT_BELAS, PANJANG_TOTAL = self.lebar(SELECTED)
            BIAYA_IRI = self.biaya((IRI_BAIK, IRI_SEDANG, IRI_RUSAK_RINGAN, IRI_RUSAK_BERAT))
            BIAYA_SDI = self.biaya((SDI_BAIK, SDI_SEDANG, SDI_RUSAK_RINGAN, SDI_RUSAK_BERAT))
        
            new_row = {
                "NO" : NO,
                "RUAS" : RUAS, 
                "PANJANG" : PANJANG, 
                "IRI_RATA" : IRI_RATA, 
                "SDI_RATA" : SDI_RATA, 
                "LEBAR_RATA" : LEBAR_RATA, 
                "IRI_BAIK" : IRI_BAIK, 
                "IRI_SEDANG" : IRI_SEDANG, 
                "IRI_RUSAK_RINGAN" : IRI_RUSAK_RINGAN,
                "IRI_RUSAK_BERAT" : IRI_RUSAK_BERAT, 
                "IRI_TOTAL" : IRI_TOTAL, 
                "SDI_BAIK" : SDI_BAIK, 
                "SDI_SEDANG" : SDI_SEDANG, 
                "SDI_RUSAK_RINGAN" : SDI_RUSAK_RINGAN, 
                "SDI_RUSAK_BERAT" : SDI_RUSAK_BERAT, 
                "SDI_TOTAL" : SDI_TOTAL,
                "LESS_ENAM" : LESS_ENAM, 
                "ENAM_TUJUH" : ENAM_TUJUH, 
                "TUJUH_EMPAT_BELAS" : TUJUH_EMPAT_BELAS ,  
                "GREATER_EMPAT_BELAS" : GREATER_EMPAT_BELAS, 
                "PANJANG_TOTAL" : PANJANG_TOTAL , 
                "BIAYA_IRI" : BIAYA_IRI, 
                "BIAYA_SDI" : BIAYA_SDI
            }
            df = df.append(new_row, ignore_index=True)
        df.to_csv("./table_stat.csv")
        return True
    
    def generate_partial(self, NO_RUAS: str):
        NO = str(NO_RUAS)
        SELECTED = self.select(NO)
        RUAS = self.nama_ruas(SELECTED)
        PANJANG = self.panjang(SELECTED)
        IRI_RATA, SDI_RATA, LEBAR_RATA = self.rata_kondisi(SELECTED)
        IRI_BAIK, IRI_SEDANG, IRI_RUSAK_RINGAN, IRI_RUSAK_BERAT, IRI_TOTAL = self.panjang_per_kondisi(SELECTED, "KONDISI_IR")
        SDI_BAIK, SDI_SEDANG, SDI_RUSAK_RINGAN, SDI_RUSAK_BERAT, SDI_TOTAL = self.panjang_per_kondisi(SELECTED, "KONDISI_SD")
        LESS_ENAM, ENAM_TUJUH, TUJUH_EMPAT_BELAS, GREATER_EMPAT_BELAS, PANJANG_TOTAL = self.lebar(SELECTED)
        BIAYA_IRI = self.biaya((IRI_BAIK, IRI_SEDANG, IRI_RUSAK_RINGAN, IRI_RUSAK_BERAT))
        BIAYA_SDI = self.biaya((SDI_BAIK, SDI_SEDANG, SDI_RUSAK_RINGAN, SDI_RUSAK_BERAT))

        __index = self._indexInTable(NO_RUAS)
        self.panda.loc[__index, "PANJANG"] = PANJANG
        self.panda.loc[__index, "IRI_RATA"] = IRI_RATA
        self.panda.loc[__index, "SDI_RATA"] = SDI_RATA
        self.panda.loc[__index, "LEBAR_RATA"] = LEBAR_RATA
        self.panda.loc[__index, "IRI_BAIK"] = IRI_BAIK
        self.panda.loc[__index, "IRI_SEDANG"] = IRI_SEDANG
        self.panda.loc[__index, "IRI_RUSAK_RINGAN"] = IRI_RUSAK_RINGAN
        self.panda.loc[__index, "IRI_RUSAK_BERAT"] = IRI_RUSAK_BERAT
        self.panda.loc[__index, "IRI_TOTAL"] = IRI_TOTAL
        self.panda.loc[__index, "SDI_BAIK"] = SDI_BAIK
        self.panda.loc[__index, "SDI_SEDANG"] = SDI_SEDANG
        self.panda.loc[__index, "SDI_RUSAK_RINGAN"] = SDI_RUSAK_RINGAN
        self.panda.loc[__index, "SDI_RUSAK_BERAT"] = SDI_RUSAK_BERAT
        self.panda.loc[__index, "SDI_TOTAL"] = SDI_TOTAL
        self.panda.loc[__index, "LESS_ENAM"] = LESS_ENAM
        self.panda.loc[__index, "ENAM_TUJUH"] = ENAM_TUJUH
        self.panda.loc[__index, "TUJUH_EMPAT_BELAS"] = TUJUH_EMPAT_BELAS
        self.panda.loc[__index, "GREATER_EMPAT_BELAS"] = GREATER_EMPAT_BELAS
        self.panda.loc[__index, "PANJANG_TOTAL"] = PANJANG_TOTAL
        self.panda.loc[__index, "BIAYA_IRI"] = BIAYA_IRI
        self.panda.loc[__index, "BIAYA_SDI"] = BIAYA_SDI
        
        self.panda.to_csv("./table_stat.csv")
        return True

In [11]:
data = statistik("./Kondisi_100/KONDISI_100.shp")
select = data.select("045")
# data.generate()
select

Empty GeoDataFrame
Columns: [STA, LEBAR_JALA, BAHU_KIRI, BAHU_KANAN, TROTOAR_KI, TROTOAR_KA, PERKERASAN, IRI, SDI, KONDISI_IR, KONDISI_SD, X, Y, RUAS, P_SEGMEN, KEY, LAYER, NO, NO_RUAS, NAMA_RUAS, PANJANG, LINTAS, LINTAS_RUA, TITIK_AWAL, TITIK_AKHI, PANJANG_RE, COLOR_IRI, COLOR_SDI, COLOR_PERK, x_1, y_1, COLOR_PE_1, COLOR_PE_2, geometry]
Index: []

In [14]:
data = gpd.read_file("./Kondisi_100/KONDISI_100.shp")
data.head()

,STA,LEBAR_JALA,BAHU_KIRI,BAHU_KANAN,TROTOAR_KI,TROTOAR_KA,PERKERASAN,IRI,SDI,KONDISI_IR,KONDISI_SD,X,Y,RUAS,P_SEGMEN,KEY,LAYER,NO,NO_RUAS,NAMA_RUAS,PANJANG,LINTAS,LINTAS_RUA,TITIK_AWAL,TITIK_AKHI,PANJANG_RE,COLOR_IRI,COLOR_SDI,COLOR_PERK,COLOR_PE_1,geometry
0,90.09999999999999,7,2,2,0,0,ASPAL,5,3,SEDANG,BAIK,341486.435149,9.793842e+06,N.001,0.05,001,JALAN,1.0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.15,Lintas Timur,Lintas Timur Jambi,Patok Km 146,Gapura Batas Prov. Jambi,356675.093851,yellow,green,black,black,"LINESTRING (11529858.346 -207578.268, 11529946..."
1,90,7,2,2,0,0,ASPAL,4,8,BAIK,BAIK,341574.805258,9.793796e+06,N.001,0.1,001,JALAN,1.0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.15,Lintas Timur,Lintas Timur Jambi,Patok Km 146,Gapura Batas Prov. Jambi,356675.093851,green,green,black,black,"LINESTRING (11529946.709 -207624.585, 11530035..."
2,89.90000000000001,7,2,2,0,0,ASPAL,7,3,SEDANG,BAIK,341663.200086,9.793750e+06,N.001,0.1,001,JALAN,1.0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.15,Lintas Timur,Lintas Timur Jambi,Patok Km 146,Gapura Batas Prov. Jambi,356675.093851,yellow,green,black,black,"LINESTRING (11530035.121 -207670.928, 11530123..."
3,89.8,7,2,2,0,0,ASPAL,8,3,SEDANG,BAIK,341751.594913,9.793705e+06,N.001,0.1,001,JALAN,1.0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.15,Lintas Timur,Lintas Timur Jambi,Patok Km 146,Gapura Batas Prov. Jambi,356675.093851,yellow,green,black,black,"LINESTRING (11530123.533 -207717.271, 11530211..."
4,89.7,7,2,2,0,0,ASPAL,4,3,SEDANG,BAIK,341839.989741,9.793659e+06,N.001,0.1,001,JALAN,1.0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.15,Lintas Timur,Lintas Timur Jambi,Patok Km 146,Gapura Batas Prov. Jambi,356675.093851,yellow,green,black,black,"LINESTRING (11530211.945 -207763.614, 11530300..."

In [19]:
if 'COLOR_IRI' not in data:
    print("gak ada")
else:
    print("ada")

ada

In [239]:
a = select.SDI * select.P_SEGMEN
b = select.P_SEGMEN.sum()
c = 68.35
b*c


# 90.15

6161.7525

In [199]:
%timeit len(select.P_SEGMEN)

8.23 µs ± 68.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [242]:
mytable = pd.read_csv("./table_stat.csv", index_col=0)
mytable

,NO,RUAS,PANJANG,IRI_RATA,SDI_RATA,LEBAR_RATA,IRI_BAIK,IRI_SEDANG,IRI_RUSAK_RINGAN,IRI_RUSAK_BERAT,...,SDI_RUSAK_RINGAN,SDI_RUSAK_BERAT,SDI_TOTAL,LESS_ENAM,ENAM_TUJUH,TUJUH_EMPAT_BELAS,GREATER_EMPAT_BELAS,PANJANG_TOTAL,BIAYA_IRI,BIAYA_SDI
0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.150,9.245147,68.062673,7.121464,9.8,40.150,18.600,21.60,...,36.0,0.3,90.150,0.0,50.250,39.90,0.000,90.150,2.653071e+11,1.527405e+11
1,002.,PENINGGALAN - SEI LILIN,33.941,9.465514,69.509531,6.886032,4.7,13.200,7.341,8.70,...,15.9,0.1,33.941,0.0,31.641,2.30,0.000,33.941,1.061317e+11,6.688745e+10
2,003.,SEI LILIN - BETUNG,43.800,7.954338,55.525114,7.000000,6.5,22.500,7.800,7.00,...,13.0,0.3,43.800,0.0,43.800,0.00,0.000,43.800,9.387880e+10,5.736500e+10
3,004.,BETUNG - BTS. KOTA PALEMBANG,56.160,6.670584,33.367165,7.062286,3.5,42.760,9.300,0.60,...,6.5,0.1,56.160,0.6,33.800,21.76,0.000,56.160,4.558980e+10,2.996600e+10
4,004.1AK,JLN. R. SUKAMTO (PALEMBANG),1.445,4.861592,28.719723,15.000000,0.6,0.845,0.000,0.00,...,0.0,0.0,1.445,0.0,0.000,0.00,1.445,1.445,7.225000e+07,7.225000e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,043.11K,JLN. A. YANI,2.800,4.571429,35.535714,21.000000,1.2,1.600,0.000,0.00,...,0.3,0.0,2.800,0.0,0.000,0.00,2.800,2.800,1.400000e+08,1.353800e+09
84,044,JLN. LINGKAR TIMUR KOTA PRABUMULI,21.300,11.816901,76.657277,12.091080,3.8,4.200,5.800,7.50,...,7.5,6.2,21.300,0.0,0.000,21.00,0.300,21.300,8.895680e+10,8.466800e+10
85,045,PRAMBUMULIH - BERIINGIN,29.950,6.742905,81.676127,7.007012,4.5,16.500,8.650,0.30,...,11.7,0.2,29.950,0.2,24.250,5.50,0.000,29.950,3.907240e+10,5.055370e+10
86,046,BERINGIN - BTS. KAB. OKU,37.750,7.441060,86.157616,7.070728,4.8,18.400,13.400,1.15,...,17.0,0.1,37.750,0.0,21.300,16.45,0.000,37.750,6.598240e+10,7.152850e+10
87,047,BTS. KAB. OKU - BATURAJA,32.500,10.203077,90.563077,7.070154,1.0,12.200,12.000,7.30,...,16.7,1.2,32.500,0.0,15.500,17.00,0.000,32.500,1.128840e+11,7.950120e+10

In [184]:
pd.read_csv("./table_stat_new.csv", index_col=0).head(5)

,NO,RUAS,PANJANG,IRI_RATA,SDI_RATA,LEBAR_RATA,IRI_BAIK,IRI_SEDANG,IRI_RUSAK_RINGAN,IRI_RUSAK_BERAT,...,SDI_RUSAK_RINGAN,SDI_RUSAK_BERAT,SDI_TOTAL,LESS_ENAM,ENAM_TUJUH,TUJUH_EMPAT_BELAS,GREATER_EMPAT_BELAS,PANJANG_TOTAL,BIAYA_IRI,BIAYA_SDI
0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.150017,9.245145,68.062660,7.121461,9.8,40.150001,18.600,21.6,...,36.000001,0.3,90.150001,0.0,50.250001,39.900001,0.000,90.150001,2.653071e+11,1.527405e+11
1,002.,PENINGGALAN - SEI LILIN,33.941000,9.465514,69.509531,6.886032,4.7,13.200000,7.341,8.7,...,15.900000,0.1,33.941000,0.0,31.641000,2.300000,0.000,33.941000,1.061317e+11,6.688745e+10
2,003.,SEI LILIN - BETUNG,43.800000,7.954338,56.694064,7.000000,6.5,22.500000,7.800,7.0,...,13.000000,0.3,43.800000,0.0,43.800000,0.000000,0.000,43.800000,9.387880e+10,5.736500e+10
3,004.,BETUNG - BTS. KOTA PALEMBANG,56.160000,6.670584,33.367165,7.062286,3.5,42.760000,9.300,0.6,...,6.500000,0.1,56.160000,0.6,33.800000,21.760000,0.000,56.160000,4.558980e+10,2.996600e+10
4,004.1AK,JLN. R. SUKAMTO (PALEMBANG),1.445000,4.861592,28.719723,15.000000,0.6,0.845000,0.000,0.0,...,0.000000,0.0,1.445000,0.0,0.000000,0.000000,1.445,1.445000,7.225000e+07,7.225000e+07

In [102]:
import numpy as np

In [119]:
a = (select.P_SEGMEN.astype(np.float64) * select.SDI.astype(np.float64)).sum()

In [121]:
b = select.P_SEGMEN.astype(np.float64).sum()

In [122]:
a/b

68.34664448141984

In [145]:
import pandas as pd
data = pd.read_csv("./table_stat.csv", index_col=0)
data

,NO,RUAS,PANJANG,IRI_RATA,SDI_RATA,LEBAR_RATA,IRI_BAIK,IRI_SEDANG,IRI_RUSAK_RINGAN,IRI_RUSAK_BERAT,...,SDI_RUSAK_RINGAN,SDI_RUSAK_BERAT,SDI_TOTAL,LESS_ENAM,ENAM_TUJUH,TUJUH_EMPAT_BELAS,GREATER_EMPAT_BELAS,PANJANG_TOTAL,BIAYA_IRI,BIAYA_SDI
0,001.,BTS. PROV. JAMBI - PENINGGALAN,90.150,9.245147,68.346644,7.121464,9.8,40.150,18.600,21.60,...,36.0,0.3,90.150,0.0,50.250,39.90,0.000,90.150,2.653071e+11,1.527405e+11
1,002.,PENINGGALAN - SEI LILIN,33.941,9.465514,69.509531,6.886032,4.7,13.200,7.341,8.70,...,15.9,0.1,33.941,0.0,31.641,2.30,0.000,33.941,1.061317e+11,6.688745e+10
2,003.,SEI LILIN - BETUNG,43.800,7.954338,56.694064,7.000000,6.5,22.500,7.800,7.00,...,13.0,0.3,43.800,0.0,43.800,0.00,0.000,43.800,9.387880e+10,5.736500e+10
3,004.,BETUNG - BTS. KOTA PALEMBANG,56.160,6.670584,33.367165,7.062286,3.5,42.760,9.300,0.60,...,6.5,0.1,56.160,0.6,33.800,21.76,0.000,56.160,4.558980e+10,2.996600e+10
4,004.1AK,JLN. R. SUKAMTO (PALEMBANG),1.445,4.861592,28.719723,15.000000,0.6,0.845,0.000,0.00,...,0.0,0.0,1.445,0.0,0.000,0.00,1.445,1.445,7.225000e+07,7.225000e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,043.11K,JLN. A. YANI,2.800,4.571429,35.535714,21.000000,1.2,1.600,0.000,0.00,...,0.3,0.0,2.800,0.0,0.000,0.00,2.800,2.800,1.400000e+08,1.353800e+09
84,044,JLN. LINGKAR TIMUR KOTA PRABUMULI,21.300,11.816901,149.971831,12.091080,3.8,4.200,5.800,7.50,...,7.5,6.2,21.300,0.0,0.000,21.00,0.300,21.300,8.895680e+10,8.466800e+10
85,045,PRAMBUMULIH - BERIINGIN,29.950,6.742905,83.385643,7.007012,4.5,16.500,8.650,0.30,...,11.7,0.2,29.950,0.2,24.250,5.50,0.000,29.950,3.907240e+10,5.055370e+10
86,046,BERINGIN - BTS. KAB. OKU,37.750,7.441060,86.835762,7.070728,4.8,18.400,13.400,1.15,...,17.0,0.1,37.750,0.0,21.300,16.45,0.000,37.750,6.598240e+10,7.152850e+10
87,047,BTS. KAB. OKU - BATURAJA,32.500,10.203077,95.289231,7.070154,1.0,12.200,12.000,7.30,...,16.7,1.2,32.500,0.0,15.500,17.00,0.000,32.500,1.128840e+11,7.950120e+10

In [33]:
class rekap:
    import pandas as pd
    def __init__(self, namafile):
        self.namafile = namafile
    
    def generate(self):
        df = self.pd.read_csv(self.namafile, index_col=0)
        
        SUM_IRI_BAIK = df.IRI_BAIK.sum()
        SUM_IRI_SEDANG = df.IRI_SEDANG.sum()
        SUM_IRI_RUSAK_RINGAN = df.IRI_RUSAK_RINGAN.sum()
        SUM_IRI_RUSAK_BERAT = df.IRI_RUSAK_BERAT.sum()
        TOTAL_IRI = SUM_IRI_BAIK + SUM_IRI_SEDANG + SUM_IRI_RUSAK_RINGAN + SUM_IRI_RUSAK_BERAT
        IRI_MANTAP = (SUM_IRI_BAIK + SUM_IRI_SEDANG) / TOTAL_IRI
        IRI_TIDAK_MANTAP = (SUM_IRI_RUSAK_RINGAN + SUM_IRI_RUSAK_BERAT) / TOTAL_IRI
        
        SUM_SDI_BAIK = df.SDI_BAIK.sum()
        SUM_SDI_SEDANG = df.SDI_SEDANG.sum()
        SUM_SDI_RUSAK_RINGAN = df.SDI_RUSAK_RINGAN.sum()
        SUM_SDI_RUSAK_BERAT = df.SDI_RUSAK_BERAT.sum()
        TOTAL_SDI = SUM_SDI_BAIK + SUM_SDI_SEDANG + SUM_SDI_RUSAK_RINGAN + SUM_SDI_RUSAK_BERAT
        SDI_MANTAP = (SUM_SDI_BAIK + SUM_SDI_SEDANG) / TOTAL_SDI
        SDI_TIDAK_MANTAP = (SUM_SDI_RUSAK_RINGAN + SUM_SDI_RUSAK_BERAT) / TOTAL_SDI
        
        
        data = {
            "IRI": [SUM_IRI_BAIK, SUM_IRI_SEDANG, SUM_IRI_RUSAK_RINGAN, SUM_IRI_RUSAK_BERAT, TOTAL_IRI, IRI_MANTAP, IRI_TIDAK_MANTAP],
            "SDI": [SUM_SDI_BAIK, SUM_SDI_SEDANG, SUM_SDI_RUSAK_RINGAN, SUM_SDI_RUSAK_BERAT, TOTAL_SDI, SDI_MANTAP, SDI_TIDAK_MANTAP]
         }
        
        dataframe = self.pd.DataFrame(data, columns = ["IRI", "SDI"])
        
        return dataframe

In [50]:
data = rekap("./table_stat.csv")
gen = data.generate()

In [42]:
import pandas as pd
data = pd.read_csv("./table_stat.csv", index_col=0)

In [64]:
a  = data.NO[data.NO == "001."].index.tolist()

In [72]:
data.loc[data['NO'] == "002."].index[0]

1

In [36]:
import pandas as pd
data = {"Nama" :["a", "b", "b"],
       "Nilai" : [10, 100, 100]}

df = pd.DataFrame(data)

In [41]:
df.loc[1, "Nama"] = "C"
df

  Nama  Nilai
0    a     10
1    C    100
2    b    100

In [142]:
my_data = statistik("./Kondisi_100/KONDISI_100.shp")

selected = my_data.select("005.11K")
round((selected.P_SEGMEN * selected.IRI).sum()/selected.P_SEGMEN.sum(),2 )

6.13

In [135]:
selected.IRI

2563    6
2564    4
2565    4
2566    5
2567    4
       ..
2723    6
2724    5
2725    5
2726    7
2727    5
Name: IRI, Length: 165, dtype: int64

5.0547112462006085

In [2]:
from bokeh.plotting import ColumnDataSource, figure, output_file, show

output_file("toolbar.html")

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', 'b', 'C', 'd', 'E'],
))



p = figure(plot_width=400, plot_height=400, tooltips=TOOLTIPS,
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)

In [36]:
from bokeh.models import HoverTool
source = ColumnDataSource(
        data=dict(
            x=[1, 2, 3, 4, 5],
            y=[2, 5, 8, 2, 7],
            desc=['A', 'b', 'C', 'd', 'E'],
            imgs = [
                'http://docs.bokeh.org/static/snake.jpg',
                'http://docs.bokeh.org/static/snake2.png',
                'http://docs.bokeh.org/static/snake3D.png',
                'http://docs.bokeh.org/static/snake4_TheRevenge.png',
                'http://docs.bokeh.org/static/snakebite.jpg'
            ]
        )
    )

hover = HoverTool(tooltips="""
            <div style="margin : 10px 10px 10px 10px; ">
                <img
                    src="@imgs" height="100" alt="@imgs" width="100"
                    style="float: left; margin: 0px 15px 15px 0px;"
                    border="2"/>
            </div>
            <div>
                <p> index : $index </p>
                <p> Desc : @desc </p>
                <p> (x, y) : ($x, $y) </p>
            </div>
        """)

TOOLTIPS = [
    ("index", "<b>$index</b>"),
    ("(x,y)", "($x, $y)"),
    ("desc", "@desc"),
]

p = figure(plot_width=400, plot_height=400,
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

p.add_tools(hover)
show(p)